#########################################################################################
#                                                                                       #
# This program and the accompanying materials are made available under the terms of the #
# Eclipse Public License v2.0 which accompanies this distribution, and is available at  #
# https://www.eclipse.org/legal/epl-v20.html                                            #
#                                                                                       #
# SPDX-License-Identifier: EPL-2.0                                                      #
#                                                                                       #
# Copyright IBM Corporation 2020                                                        #
#                                                                                       #
#########################################################################################
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zowe-api-ml.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: discovery
  ports:
    - protocol: TCP
      port: {{ .Values.discoveryService.service.port }}
      targetPort: {{ .Values.discoveryService.service.port }}
