apiVersion: v2
name: zowe-api-ml
description: A Helm chart for the Zowe API Mediation Layer
type: application
version: 0.1.0
appVersion: 1.18.0
home: https://github.com/zowe/zowe-container-sample
sources:
- https://github.com/zowe/zowe-container-sample
maintainers:
- name: Mark Hollands
  url: https://github.com/markjhollands