#########################################################################################
#                                                                                       #
# This program and the accompanying materials are made available under the terms of the #
# Eclipse Public License v2.0 which accompanies this distribution, and is available at  #
# https://www.eclipse.org/legal/epl-v20.html                                            #
#                                                                                       #
# SPDX-License-Identifier: EPL-2.0                                                      #
#                                                                                       #
# Copyright IBM Corporation 2020                                                        #
#                                                                                       #
# Static definition for z/OSMF                                                          #
#                                                                                       #
# Additional Usage:                                                                     #
# If you do not add the z/OSMF server certificate to the Gateway Service truststore,    #
# you must add the following configuration to docker/apiml/gateway-service.yml:         #
#                                                                                       #
#   apiml:                                                                              #
#       security:                                                                       #
#           verifySslCertificatesOfServices: false                                      #
#                                                                                       #
#########################################################################################
services:
  - serviceId: ibmzosmf
    title: IBM z/OSMF
    description: IBM z/OS Management Facility REST API service
    catalogUiTileId: zosmf
    instanceBaseUrls:
      - https://zosmf.mymainframe.com:32070/ # scheme://hostname:port/contextPath
    homePageRelativeUrl: # Home page of the z/OSMF service
    routes:
      - gatewayUrl: api
        serviceRelativeUrl: /
      - gatewayUrl: ui
        serviceRelativeUrl: /
    authentication:
      scheme: zosmf
    apiInfo:
      - apiId: com.ibm.zosmf
        gatewayUrl: api
        version: 2.4.0
        documentationUrl: https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.izua700/IZUHPINFO_RESTServices.htm
        swaggerUrl:

catalogUiTiles:
  zosmf:
    title: z/OSMF services
    description: IBM z/OS Management Facility REST services
